### ISSUE TITLE
RubyVersionmanager: Doesn't clean up on failure

### ISSUE THREAD

**Issue by patricklauer** [adjust/p5-Ruby-VersionManager#4]
If there's any error condition (in this case it was an OOM) then re-running the install of ruby-vmanager will abort like this since there's a .ext/rdoc directory already.

Just deleting the dir will allow it to build (if there's no OOM or other disturbance)

```
Generating RDoc documentation
uncommon.mk:420: recipe for target 'rdoc' failed
STDERR:
Using built-in specs.
COLLECT_GCC=/usr/x86_64-pc-linux-gnu/gcc-bin/4.8.5/gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-pc-linux-gnu/4.8.5/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /var/tmp/portage/sys-devel/gcc-4.8.5/work/gcc-4.8.5/configure --host=x86_64-pc-linux-gnu --build=x86_64-pc-linux-gnu --prefix=/usr --bindir=/usr/x86_64-pc-linux-gnu/gcc-bin/4.8.5 --includedir=/usr/lib/gcc/x86_64-pc-linux-gnu/4.8.5/include --datadir=/usr/share/gcc-data/x86_64-pc-linux-gnu/4.8.5 --mandir=/usr/share/gcc-data/x86_64-pc-linux-gnu/4.8.5/man --infodir=/usr/share/gcc-data/x86_64-pc-linux-gnu/4.8.5/info --with-gxx-include-dir=/usr/lib/gcc/x86_64-pc-linux-gnu/4.8.5/include/g++-v4 --with-python-dir=/share/gcc-data/x86_64-pc-linux-gnu/4.8.5/python --enable-languages=c,c++ --enable-obsolete --enable-secureplt --disable-werror --with-system-zlib --enable-nls --without-included-gettext --enable-checking=release --with-bugurl=https://bugs.gentoo.org/ --with-pkgversion='Gentoo Hardened 4.8.5 p1.3, pie-0.6.2' --enable-esp --enable-libstdcxx-time --enable-shared --enable-threads=posix --enable-__cxa_atexit --enable-clocale=gnu --disable-multilib --with-multilib-list=m64 --disable-altivec --disable-fixed-point --enable-targets=all --disable-libgcj --enable-libgomp --disable-libmudflap --disable-libssp --disable-libquadmath --enable-lto --without-cloog --disable-libsanitizer
Thread model: posix
gcc version 4.8.5 (Gentoo Hardened 4.8.5 p1.3, pie-0.6.2) 

Directory .ext/rdoc already exists, but it looks like it isn't an RDoc directory.

Because RDoc doesn't want to risk destroying any of your existing files,
you'll need to specify a different output directory name (using the --op <dir>
option)

/var/lib/postgresql/.ruby_vmanager/source/ruby-2.1.7/lib/rdoc/rdoc.rb:108:in `error'
        /var/lib/postgresql/.ruby_vmanager/source/ruby-2.1.7/lib/rdoc/rdoc.rb:208:in `rescue in setup_output_dir'
        /var/lib/postgresql/.ruby_vmanager/source/ruby-2.1.7/lib/rdoc/rdoc.rb:195:in `setup_output_dir'
        /var/lib/postgresql/.ruby_vmanager/source/ruby-2.1.7/lib/rdoc/rdoc.rb:475:in `document'
        ./bin/rdoc:20:in `<main>'

make: *** [rdoc] Error 1
cp: target â/var/lib/postgresql/.ruby_vmanager/rubies/2.1/ruby-2.1.7/binâ is not a directory
tar: This does not look like a tar archive

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Can't chdir('/var/lib/postgresql/.ruby_vmanager/source/rubygems-1.3.7'): No such file or directory at /usr/lib64/perl5/vendor_perl/5.20.2/Ruby/VersionManager.pm line 488 at /usr/lib64/perl5/vendor_perl/5.22.0/Rex/Commands/Run.pm line 302.

[2015-10-16 22:51:51] 192.168.122.158 ERROR - Error running t/postgresql.t: Died at /usr/lib64/perl5/vendor_perl/5.22.0/Rex/Interface/Executor/Default.pm line 62.
```

**Comment by alip** [comment]
I have recently hit the same problem. #8 should fix this.
